### ISSUE TITLE
Class times on H days are sometimes wrong

### ISSUE THREAD

**Issue by Kizjkre** [wangl5/veracross-cgs-schedule#1]
# Example:
![Untitled](https://user-images.githubusercontent.com/24882191/64667687-7ee44d80-d40f-11e9-9ded-5795ae7ddaa0.png)

**Comment by Kizjkre** [comment]
Not just H days, but all days with the last block free.

**Comment by liamjwang** [comment]
The program scrapes the html of the veracross pages, so, unfortunately, there is currently no method to determine when classes end.
